{% set name = "just" %}
{% set version = "1.56.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casey/just/archive/{{ version }}.tar.gz
  sha256: 145cb76ccd858da30ee56de884dad9241b2706140bcf9ae189dfda5e5a62ed52

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - just --help

about:
  home: https://github.com/casey/just
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: just is a handy way to save and run project-specific commands.

extra:
  recipe-maintainers:
    - dbast
