{% set name = "just" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casey/just/archive/{{ version }}.tar.gz
  sha256: 1a5ea3e3677f97eda36b9257b774e00a64985820ba678c584827e9409f838e1c

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - cargo-bundle-licenses

test:
  commands:
    - just --help

about:
  home: https://github.com/casey/just
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: just is a handy way to save and run project-specific commands.

extra:
  recipe-maintainers:
    - kellpossible
    - dbast
