{% set name = "just" %}
{% set version = "1.57.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/casey/just/archive/{{ version }}.tar.gz
  sha256: 905c556aad3c0a4b0376db98b706a9aa3485fcf50a30377d50737bf20f3792cb

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
    - cargo-bundle-licenses

test:
  commands:
    - just --help

about:
  home: https://github.com/casey/just
  license: CC0-1.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: just is a handy way to save and run project-specific commands.

extra:
  recipe-maintainers:
    - dbast
